//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaThi
    {
        public int IDKetQua { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string IdBangThi { get; set; }
        public Nullable<int> SoCauDung { get; set; }
        public Nullable<int> SoCauSai { get; set; }
        public Nullable<System.TimeSpan> ThoiGianLamBai { get; set; }
    
        public virtual BangThi BangThi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
