//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangThi()
        {
            this.KetQuaThi = new HashSet<KetQuaThi>();
            this.CauHoi = new HashSet<CauHoi>();
        }
    
        public string IdBangThi { get; set; }
        public string TenBangThi { get; set; }
        public System.DateTime GioThi { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaThi> KetQuaThi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHoi> CauHoi { get; set; }
    }
}
